---
name: pull-request-comment
on:
  issue_comment:
    types: [created, edited]

jobs:
  full-tests:
    runs-on: [ubuntu-latest]
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/test'}}
    env:
      DO_TOKEN: ${{ secrets.DO_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.4"
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - run: |
          make test options="-v"
